# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}

# Load a restored tab as soon as it takes focus.
# Type: Bool
c.session.lazy_restore = True

# Additional arguments to pass to Qt, without leading `--`. With
# QtWebEngine, some Chromium arguments (see
# https://peter.sh/experiments/chromium-command-line-switches/ for a
# list) will work.
# Type: List of String
c.qt.args = ['ignore-gpu-blacklist', 'enable-accelerated-2d-canvas', 'enable-gpu-memory-buffer-video-frames', 'enable-gpu-rasterization', 'enable-native-gpu-memory-buffers', 'enable-oop-rasterization', 'enable-zero-copy']

# Force software rendering for QtWebEngine. This is needed for
# QtWebEngine to work with Nouveau drivers and can be useful in other
# scenarios related to graphic issues.
# Type: String
# Valid values:
#   - software-opengl: Tell LibGL to use a software implementation of GL (`LIBGL_ALWAYS_SOFTWARE` / `QT_XCB_FORCE_SOFTWARE_OPENGL`)
#   - qt-quick: Tell Qt Quick to use a software renderer instead of OpenGL. (`QT_QUICK_BACKEND=software`)
#   - chromium: Tell Chromium to disable GPU support and use Skia software rendering instead. (`--disable-gpu`)
#   - none: Don't force software rendering.
c.qt.force_software_rendering = 'qt-quick'

# Which Chromium process model to use. Alternative process models use
# less resources, but decrease security and robustness. See the
# following pages for more details:    -
# https://www.chromium.org/developers/design-documents/process-models
# - https://doc.qt.io/qt-5/qtwebengine-features.html#process-models
# Type: String
# Valid values:
#   - process-per-site-instance: Pages from separate sites are put into separate processes and separate visits to the same site are also isolated.
#   - process-per-site: Pages from separate sites are put into separate processes. Unlike Process per Site Instance, all visits to the same site will share an OS process. The benefit of this model is reduced memory consumption, because more web pages will share processes. The drawbacks include reduced security, robustness, and responsiveness.
#   - single-process: Run all tabs in a single process. This should be used for debugging purposes only, and it disables `:open --private`.
c.qt.process_model = 'process-per-site-instance'

# Turn on Qt HighDPI scaling. This is equivalent to setting
# QT_AUTO_SCREEN_SCALE_FACTOR=1 or QT_ENABLE_HIGHDPI_SCALING=1 (Qt >=
# 5.14) in the environment. It's off by default as it can cause issues
# with some bitmap fonts. As an alternative to this, it's possible to
# set font sizes and the `zoom.default` setting.
# Type: Bool
c.qt.highdpi = False

# Always restore open sites when qutebrowser is reopened. Without this
# option set, `:wq` (`:quit --save`) needs to be used to save open tabs
# (and restore them), while quitting qutebrowser in any other way will
# not save/restore the session. By default, this will save to the
# session which was last loaded. This behavior can be customized via the
# `session.default_name` setting.
# Type: Bool
c.auto_save.session = True

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Allow websites to request geolocations.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.geolocation', True, 'https://earth.google.com')

# Allow websites to request geolocations.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.geolocation', False, 'https://www.homedepot.com')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.100.89.138.29/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.192.168.1.1/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.ameridroid.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.anniv.co/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.anthonyholden.tumblr.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.apps.irs.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.apps.nationalmap.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.askinglot.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.auth.atlassian.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.boardgamegeek.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.broadbandmap.fcc.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.bugs.archlinux.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.calendar.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.cardgames.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.ccwu.me/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.channelstore.roku.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.clearlinux.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.cloud.ibm.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.cobaltsoul.pdxhub.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.codeparade.itch.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.community.ui.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.costco.interstatebatteries.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.cryptpad.fr/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.datdot.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.dev.scuttlebutt.nz/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.developer.arm.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.discord.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.discussions.apple.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.dns.he.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.docs.hetzner.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.docs.invidious.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.earth.nullschool.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.everymac.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.fiberine.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.firstlook.media/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.floss.social/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.flourish.studio/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.forum.openmediavault.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.framagit.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.fundoss.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.gateway.foresee.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.gingerhazing.gumroad.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.git.ophanim.de/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.groups.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.gsuitetips.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.help.ui.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.hn.algolia.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.html.duckduckgo.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.hydra.cons.org.nz/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.hydra.mcwhirter.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.itch.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.jellyfin.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.kde.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.keys.openpgp.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.killsixbilliondemons.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.login.tailscale.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.manual.seafile.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.mesgmy.ebay.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.metal.equinix.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.mybinder.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.mynoise.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.necropoliscomic.tumblr.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.nextdoor.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.notebooks.azure.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.pcsrefurbished.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.pine64.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.pkgs.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.portland.craigslist.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.projects.fivethirtyeight.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.rhadhesives.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.ridewithgps.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.rosden.itch.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.rubjo.github.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.sa.www4.irs.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.scrabble.77177.de/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.serverfault.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.shop.centurylink.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.shopkits.eink.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.social.mcwhirter.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.soundcloud.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.spectrum-os.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.stackoverflow.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.start.atlassian.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.stateparks.oregon.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.store.santansolar.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.surfshark.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.tailscale.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.thethinkingshop.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.towardsdatascience.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.trello.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.view.matrix.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.wayfarervans.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.web.archive.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.webcache.googleusercontent.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.wholesale.frontiercoop.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.worldview.earthdata.nasa.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.aliexpress.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.armbian.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.autowrecking.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.centurylink.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.checklifeline.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.clearos.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.comic-rocket.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.costco.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.d3-graph-gallery.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.data-to-viz.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.dell.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.dropbox.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.etsy.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.fcc.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.frontieroffers.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.generatorland.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.goodreads.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.harborfreight.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.homedepot.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.ibm.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.inaturalist.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.instagram.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.interstatebatteries.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.irs.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.irv2.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.isc.ro/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.kickstarter.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.mobileread.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.newegg.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.newspapers.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.nps.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.openprinting.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.oregonhikers.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.pine64.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.pinterest.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.pogo.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.providence.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.quora.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.raspberrypi.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.recreation.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.reflectixinc.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.reservecalifornia.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.sewingpartsonline.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.shift2bikes.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.sparkfun.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.stephouse.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.taxact.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.tumblr.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.twitch.tv/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.van-magazine.fr/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.whistleout.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.xfinity.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.zefrank.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.2020.nixcon.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.alternativeto.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.app.cachix.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.archive.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.asciinema.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.askubuntu.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.bitbucket.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.blog.system76.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.briansunter.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.buster.substack.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.channels.nixos.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.cloud.breab.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.co-opcreditunions.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.codeberg.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.codereview.qt-project.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.crates.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.developer.blender.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.discourse.nixos.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.doodle.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.earth.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.faq.i3wm.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.foodnotbombs.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.gitlab.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.gitlab.freedesktop.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.gitlab.gnome.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.guix.gnu.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.hydra.nix-community.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.hydra.nixos.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.id.atlassian.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.jirafeau.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.kungsgeten.github.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.meet.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.melpa.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.mermaid-js.github.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.multcolib.kanopy.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.multcolib.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.nixos.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.nixos.wiki/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.olis.leg.state.or.us/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.organice.200ok.ch/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.pdx.zoom.us/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.pop.system76.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.postimg.cc/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.roamresearch.typeform.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.search.nixos.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.selfoss.aditu.de/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.static.crunchyroll.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.subscription.packtpub.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.support.apple.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.system76.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.tiddlywiki.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.translate.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.trends.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.twitter.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.verily.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.wayfire.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.whatismyipaddress.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.adcoservice.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.arcmanorbooks.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.bhphotovideo.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.compositional.fm/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.hackster.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.hulu.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.icloud.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.ifixit.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.kanopy.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.kite.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.mesa3d.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.mongodb-is-web-scale.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.netdata.cloud/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.neweggbusiness.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.notion.so/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.patreon.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.pbs.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.pcworld.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.playemulator.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.reddit.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.rivermarkcu.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.rivermarkcuonline.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.scribd.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.thehumansolution.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.usacu.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.zotero.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.xray.fm/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.chriskempson.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.thomashunter.name/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.bugreports.qt.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.mykzilla.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.phoronix.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.app.element.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.01.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.accounts.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.catalog.data.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.cse.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.digital.weather.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.docs.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.drive.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.f-droid.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.giffmex.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.github.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.jamanetwork.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.jsplumbtoolkit.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.mail.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.pay.ebay.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.pubchem.ncbi.nlm.nih.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.readwise.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.riot.im/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.roamresearch.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.signin.ebay.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.smile.amazon.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.studentaid.gov/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.superuser.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.tardigrade.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.unix.stackexchange.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.vim.liuchengxu.org/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.weatherspark.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.amazon.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.ebay.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.facebook.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.google.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.hometips.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.slant.co/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.verizonwireless.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.walgreens.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.wolframalpha.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.www.youtube.com/*')

# Enable JavaScript.
# Type: Bool
c.content.javascript.enabled = False

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.hub.docker.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.docs.influxdata.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.localhost/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.discuss.kakoune.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.nearlyfreespeech.net/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.paypal.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.digikey.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.brianlovin.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.emacs.stackexchange.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.duckduckgo.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.av.tib.eu/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.akhater.github.io/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://*.notes.huy.rocks/*')

# Allow websites to record audio.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.audio_capture', True, 'https://hangouts.google.com')

# Allow websites to record audio.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.audio_capture', True, 'https://meet.google.com')

# Allow websites to record audio.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.audio_capture', True, 'https://meet.jit.si')

# Allow websites to record audio and video.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.audio_video_capture', True, 'https://hangouts.google.com')

# Allow websites to record audio and video.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.audio_video_capture', True, 'https://meet.google.com')

# Allow websites to record audio and video.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.audio_video_capture', True, 'https://meet.jit.si')

# Allow websites to record video.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.video_capture', True, 'https://hangouts.google.com')

# Allow websites to record video.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.video_capture', True, 'https://meet.google.com')

# Allow websites to record video.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.media.video_capture', True, 'https://meet.jit.si')

# Allow websites to show notifications.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.notifications.enabled', False, 'https://www.reddit.com')

# Allow websites to register protocol handlers via
# `navigator.registerProtocolHandler`.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.register_protocol_handler', True, 'https://mail.google.com?extsrc=mailto&url=%25s')

# List of user stylesheet filenames to use.
# Type: List of File, or File
c.content.user_stylesheets = []

# Number of commands to save in the command history. 0: no history / -1:
# unlimited
# Type: Int
c.completion.cmd_history_max_items = -1

# Duration (in milliseconds) to wait before removing finished downloads.
# If set to -1, downloads are never removed.
# Type: Int
c.downloads.remove_finished = -1

# Editor (and arguments) to use for the `edit-*` commands. The following
# placeholders are defined:  * `{file}`: Filename of the file to be
# edited. * `{line}`: Line in which the caret is found in the text. *
# `{column}`: Column in which the caret is found in the text. *
# `{line0}`: Same as `{line}`, but starting from index 0. * `{column0}`:
# Same as `{column}`, but starting from index 0.
# Type: ShellCommand
c.editor.command = ['emacsclient', '-nc', '{file}']

# Enable smooth scrolling for web pages. Note smooth scrolling does not
# work with the `:scroll-px` command.
# Type: Bool
c.scrolling.smooth = True

# When to show the statusbar.
# Type: String
# Valid values:
#   - always: Always show the statusbar.
#   - never: Always hide the statusbar.
#   - in-mode: Show the statusbar when in modes other than normal mode.
c.statusbar.show = 'always'

# Position of the status bar.
# Type: VerticalPosition
# Valid values:
#   - top
#   - bottom
c.statusbar.position = 'top'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'multiple'

# Open a new window for every tab.
# Type: Bool
c.tabs.tabs_are_windows = True

# Search engines which can be used via the address bar.  Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` braces.  The following further
# placeholds are defined to configure how special characters in the
# search terms are replaced by safe characters (called 'quoting'):  *
# `{}` and `{semiquoted}` quote everything except slashes; this is the
# most   sensible choice for almost all search engines (for the search
# term   `slash/and&amp` this placeholder expands to `slash/and%26amp`).
# * `{quoted}` quotes all characters (for `slash/and&amp` this
# placeholder   expands to `slash%2Fand%26amp`). * `{unquoted}` quotes
# nothing (for `slash/and&amp` this placeholder   expands to
# `slash/and&amp`). * `{0}` means the same as `{}`, but can be used
# multiple times.  The search engine named `DEFAULT` is used when
# `url.auto_search` is turned on and something else than a URL was
# entered to be opened. Other search engines can be used by prepending
# the search engine name to the search term, e.g. `:open google
# qutebrowser`.
# Type: Dict
c.url.searchengines = {'g': 'https://google.com/search?q={}', 'DEFAULT': 'https://duckduckgo.com/?q={}', 'yt': 'http://www.youtube.com/results?search_query={}', 'wp': 'https://en.wikipedia.org/w/index.php?search={}&title=Special:Search', 'dict': 'https://wordnik.com/words/{}'}

# Hide the window decoration.  This setting requires a restart on
# Wayland.
# Type: Bool
c.window.hide_decoration = True

# Default zoom level.
# Type: Perc
c.zoom.default = '100%'

# Background color for webpages if unset (or empty to use the theme's
# color).
# Type: QtColor
c.colors.webpage.bg = 'white'

# Render all web contents using a dark theme. Example configurations
# from Chromium's `chrome://flags`:  - "With simple HSL/CIELAB/RGB-based
# inversion": Set   `colors.webpage.darkmode.algorithm` accordingly.  -
# "With selective image inversion": Set
# `colors.webpage.darkmode.policy.images` to `smart`.  - "With selective
# inversion of non-image elements": Set
# `colors.webpage.darkmode.threshold.text` to 150 and
# `colors.webpage.darkmode.threshold.background` to 205.  - "With
# selective inversion of everything": Combines the two variants   above.
# Type: Bool
c.colors.webpage.darkmode.enabled = False

# Contrast for dark mode. This only has an effect when
# `colors.webpage.darkmode.algorithm` is set to `lightness-hsl` or
# `brightness-rgb`.
# Type: Float
c.colors.webpage.darkmode.contrast = 0.0

# Bindings for normal mode
config.bind(',c', 'spawn org-capture -k j [[{url}][{title}]]')
config.bind(',l', 'config-cycle colors.webpage.darkmode.enabled ;; restart')
config.bind(',n', 'config-:cycle content.user_stylesheets "~/src/github.com/alphapapa/solarized-everything-css/css/solarized-dark/solarized-dark-all-sites.css" ""')
config.bind(',p', 'spawn --userscript password_fill {url}')
config.bind(',v', 'spawn mpv {url}')
config.bind('d', 'close')
config.bind('xs', 'config-cycle --print --pattern *://*.{url:host}/* content.javascript.enabled ;; reload')
config.bind('yo', 'yank inline [[{url}][{title}]]')
