theme = "autumn_night"

[editor]
auto-save = true
# cursorline = true
# line-number = "relative"
soft-wrap.enable = true

[editor.statusline]
left = ["version-control"]
center = ["file-name"]
right = ["mode", "selections", "position", "file-encoding", "file-type", "spinner", "diagnostics"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
# hidden = false # true = hide

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.whitespace]
[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
space = "·"
tab = "→"
tabpad = "-"

[editor.whitespace.render]
# newline = "all"
# space = "all"
# tab = "all"

## My keybinds

# fix x on empty line, see https://github.com/helix-editor/helix/discussions/1511#discussioncomment-3362549
# [keys.normal]
# x = "extend_to_line_bounds" # previously "X"
# X = "no_op"
# [keys.select]
# x = "extend_line" # previously normal mode "x"


# https://docs.helix-editor.com/remapping.html
[keys.normal."\\"]

# [keys.normal."\\".p]
# TODO: surround selection with [[]]
l = ":pipe echo -n \"[[$(cat)]]\""

# [keys.normal."\\".i]
d = ":pipe date +%Y-%m-%d|tr -d '\n'"

# Support for macro-style keybinding https://github.com/helix-editor/helix/issues/1383

# TODO: this is pretty useless. 
# minus = ":pipe sed -e 's/^/ - /'"
# broken
# i = ["open_below", "normal_mode", ":shell_insert_output echo ' - '"]
# c = ""

# src: https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
# Clipboards over registers
# At least until https://github.com/helix-editor/helix/issues/312
# [keys.normal]
# p = ["paste_clipboard_after"]
# P = ["paste_clipboard_before"]

# [keys.select]
# y = "yank_joined_to_clipboard"
# d = ["yank_joined_to_clipboard", "delete_selection"]
# p = "replace_selections_with_clipboard"
