# TODO: see if I want to crib anything, now that I know helix pretty well
# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

theme = "autumn_night"

[editor]
auto-save = true
# cursorline = true
# line-number = "relative"
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
# hidden = false # true = hide

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.whitespace]
[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
space = "·"
tab = "→"
tabpad = "-"

[editor.whitespace.render]
# newline = "all"
# space = "all"
# tab = "all"

## My keybinds

# fix x on empty line, see https://github.com/helix-editor/helix/discussions/1511#discussioncomment-3362549
# [keys.normal]
# x = "extend_to_line_bounds" # previously "X"
# X = "no_op"
# [keys.select]
# x = "extend_line" # previously normal mode "x"


# https://docs.helix-editor.com/remapping.html
[keys.normal."\\"]

# [keys.normal."\\".p]
# TODO: surround selection with [[]]
l = ":pipe echo -n \"[[$(cat)]]\""

# [keys.normal."\\".i]
d = ":pipe date +%Y-%m-%d|tr -d '\n'"

# Support for macro-style keybinding https://github.com/helix-editor/helix/issues/1383

# TODO: this is pretty useless. 
# minus = ":pipe sed -e 's/^/ - /'"
# broken
# i = ["open_below", "normal_mode", ":shell_insert_output echo ' - '"]
# c = ""

# src: https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
# Clipboards over registers ye ye
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
# Would be nice to add ya and yi, but the surround commands can't be chained
Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]

[keys.select]
# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"