# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml
theme = "autumn_night"

[editor]
auto-save = true
color-modes = true
cursorline = true
gutters = ["diagnostics", "line-numbers", "spacer"]
line-number = "relative"
mouse = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.whitespace]
[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
space = "·"
tab = "→"
tabpad = "-"

[editor.whitespace.render]
# newline = "all"
# space = "all"
# tab = "all"

## My keybinds
# https://docs.helix-editor.com/remapping.html
[keys.normal.n]
# TODO: surround selection with [[]]
l = ":pipe echo -n \"[[$(cat)]]\""
j = ":pipe echo 'TODO: open today's journal"

# TODO: this is pretty useless. 
# minus = ":pipe sed -e 's/^/ - /'"
# broken
# i = ["open_below", "normal_mode", ":shell_insert_output echo ' - '"]
# c = ""