# disabling because it makes cpu spin
# language-server.marksman.command = "marksman"
language-server.ccls.command = "ccls"
language-server.nixd.command = "nixd"

# language.markdown.language-servers = [ "marksman" ]

# # zk only works for projects with a `.zk` subdir
# # both options are bad in different ways
# # enable per-directory with a local .helix/languages.toml
# # language-server = { command = "zk", args = ["lsp"] }

[[language]]
name = "c"
auto-format = false
language-servers = [ "ccls" ]

[[language]]
name = "cpp"
auto-format = false
language-servers = [ "ccls"]
[[language]]
name = "nix"
language-servers = ["nixd"]
